menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Teaching', path: 'menu', url: 'teaching.html'}
- {name: 'Posts', path: 'menu', url: 'posts.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/BeanHam'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/bin-han-960703/'}

# Customize site text
#pagination:
#  next_page: 'Newer'
#  previous_page: 'Older'

#sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy:'

#post_date_prefix: 'Written on'
